language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
env:
  - DATABASE_URL="postgresql://localhost:5432/travis_ci_test" REDIS_URL="redis://localhost:6379/0"
services:
  - postgresql
  - redis-server
install:
  - make clean
  - make init
  - make install
  - pip install tox-travis codecov
before_script:
  - psql -c 'drop database if exists travis_ci_test;' -U postgres
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - make lint
  - make test-tox
  - make build
after_success:
  - codecov
deploy:
  provider: heroku
  api_key:
    secure: tbiD+IMIc5leARo7QZCgk2IFpaD94eymaCZlSK9bVST5TsX2amUvOnTUD0MFdJ3kYZbdvei0MCq8bK1YB85htT0O73tuW5OZjADm4FMVZKrVKXYJSobFHJaid1YOOWHbaVsYGWq0nVL+S5DqHQK2WMR7HcRcOYFqO+M7s42Uom/CKAj1i70zMJxJJ763eoXqF4pKneyq2CUWkUdyxE8LEL+KSgN1f7lv+DcanOGm3TafoTxJ9fdeYVWFMRusNXHaXtWaUaOdDded4U1MFMFpLOc9b1rhj3NpIf2blEm/rNQbB6Ky7IpfEfyiaORV7PKNubL71/cjeWEGSTqByx1KybDE25H/ZsbZXo6MiW0/CJcytkNqZbB6vk55cY6HrsRamF+M0SInExNCjvx7+wKdrov40Aamgnscc6LzLdQBMn9zkoqdttdQbd3VnpQbksXsrx+poK4O0tchPYBoKSf8gP41zz2CAocmyfoiAl+X8YrapnBldUN8KmAFfsM74DCKgHAuornTdXGYaBq6xa8BOCjpiEaA+Hr5xH31k+ffy/qiIaxwCC1aaEfUEkqs7sW829d29tqAefCeBB9yAGhAdHG/osVbD1EHR76d0P/I8JrbNnyQnNfaTNE6fCb91x6i5S83XyDR+020yBNPAtapjk9TR5D0oGEOwcd8i2b3Q08=
  app:
    master: flask-template-staging
    production: flask-template-production
  on:
    repo: derek-miller/flask-template
    python: 2.7
