language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
env:
  - DATABASE_URL="postgresql://localhost:5432/travis_ci_test" REDIS_URL="redis://localhost:6379/0"
services:
  - postgresql
  - redis-server
install:
  - make init
  - make install
  - pip install tox-travis
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - make lint
  - make test-tox
  - make build
deploy:
  provider: heroku
  api_key:
    secure: UWoxhQVsK7qpePothIPGriAKpdY8rU1RhlGsENCOpH/i5E0Gy36TeznXBLHWwWgBvT+8ex3xx4tO4hQBKIo4Ksl+zbAdrmNlHkIGJNYO1QXEy6SzQ6jFNze5MR/mSUAyp25L91kPtFj61rzBpSXhJ1A/zEbvOALLSdvjdcM11SDS30s7nGW3jVc07IRGXVlqqr8l+VUvJ1rvPg+2Hdlyny+8ko5t54+MsS7piTXY1SGzdPcyI0IojfPuwAm38erG8cFsMt+IzAl8rjL3AhjGg1ZC4/bdI0SXxHNLhaFYfz6XoiwfTcTV0ATIyojKof/WkI9vw02SIcr+s1Vgbb9GMK92W/ZJB6pTgsPZdBAAUeQHo6g0OlbgaDhKruYmfMGRJdGmIzeIcCU3xFvptWOSrhZze0T/NkiOTjMl6a0I+OiMeYMtxCwEVj6SMPlbNCZOVbO2Y/dG9nLB8Afuc5DSIVH75QeCPhDOR/0Yn+FTVcQZ2XkebTUn5ifJG1TzaqiNiLynaPzgyzvGMagd9IPgS7cKG8Jd+fA40Yy8E5+oDeqWboumRYlpxfsbgWz5rnkOu3shd5yhoq6g3mWXXKOPOSqgWJAbN9hYnwM5L1R2S04cbFaOFcfP7FJ3H01Y4k5BZU7Nx44UDbhsYnIsm7pZ1vEQDG4CAAybFIww/jb7Sa4=
  app:
    master: flask-template-staging
    production: flask-template-production
  on:
    repo: derek-miller/flask-template
    python: 2.7
