"""Initial version

Revision ID: d5cfdc5eca6d
Revises: None
Create Date: 2016-04-16 13:58:37.356613

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd5cfdc5eca6d'
down_revision = None


def upgrade():
    # commands auto generated by Alembic - please adjust!
    roles = op.create_table('roles',
                            sa.Column('id', sa.Integer(), nullable=False),
                            sa.Column('name', sa.String(length=80), nullable=True),
                            sa.Column('description', sa.String(length=255), nullable=True),
                            sa.PrimaryKeyConstraint('id'),
                            sa.UniqueConstraint('name')
                            )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(length=255), nullable=True),
                    sa.Column('last_name', sa.String(length=255), nullable=True),
                    sa.Column('email', sa.String(length=255), nullable=True),
                    sa.Column('password', sa.String(length=255), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('current_login_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('last_login_ip', sa.String(length=100), nullable=True),
                    sa.Column('current_login_ip', sa.String(length=100), nullable=True),
                    sa.Column('login_count', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('roles_users',
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], [u'roles.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], )
                    )
    # end Alembic commands
    op.bulk_insert(roles, [{'name': 'user', 'description': 'User'},
                           {'name': 'admin', 'description': 'Administrator'},
                           {'name': 'superuser', 'description': 'Superuser'}])


def downgrade():
    # commands auto generated by Alembic - please adjust!
    op.drop_table('roles_users')
    op.drop_table('users')
    op.drop_table('roles')
    # end Alembic commands
